coverage:
  badge:
    path: .github/coverage.svg
  paths:
    - coverage.out
  acceptable: 0%
comment:
  if: is_pull_request
  deletePrevious: true
summary:
  if: true
report:
  if: is_default_branch
push:
  if: is_default_branch
  message: Update by octocov [skip ci]
