// Package sqlc provides data structures for working with sqlc catalog files.
//
// The catalog represents the database schema metadata generated by sqlc,
// including schemas, tables, columns, indexes, and foreign key relationships.
package sqlc

import (
	"encoding/json"
	"os"
)

// Catalog represents the root structure of a sqlc catalog file.
// It contains all schemas and their associated database objects.
type Catalog struct {
	Schemas []Schema `json:"schemas,omitempty"`
}

// LoadCatalog loads a sqlc catalog file from the specified path and returns a Catalog struct.
// The catalog file is expected to be in JSON format as generated by sqlc.
func LoadCatalog(path string) (*Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var catalog Catalog
	if err := json.Unmarshal(data, &catalog); err != nil {
		return nil, err
	}

	return &catalog, nil
}

// Schema represents a database schema containing tables and other database objects.
type Schema struct {
	Name   string  `json:"name"`
	Tables []Table `json:"tables,omitempty"`
	Attrs
}

// Table represents a database table with its columns, indexes, and constraints.
type Table struct {
	Name        string       `json:"name"`
	Columns     []Column     `json:"columns,omitempty"`
	Indexes     []Index      `json:"indexes,omitempty"`
	PrimaryKey  *Index       `json:"primary_key,omitempty"`
	ForeignKeys []ForeignKey `json:"foreign_keys,omitempty"`
	Attrs
}

// Column represents a table column with its name, data type, and nullability.
type Column struct {
	Name string `json:"name"`
	Type string `json:"type,omitempty"`
	Null bool   `json:"null,omitempty"`
	Attrs
}

// Index represents a database index on one or more columns or expressions.
type Index struct {
	Name   string      `json:"name,omitempty"`
	Unique bool        `json:"unique,omitempty"`
	Parts  []IndexPart `json:"parts,omitempty"`
}

// IndexPart represents a single part of an index, which can be either a column or an expression.
type IndexPart struct {
	Desc   bool   `json:"desc,omitempty"`
	Column string `json:"column,omitempty"`
	Expr   string `json:"expr,omitempty"`
}

// ForeignKey represents a foreign key constraint linking columns in this table
// to columns in a referenced table.
type ForeignKey struct {
	Name       string   `json:"name"`
	Columns    []string `json:"columns,omitempty"`
	References struct {
		Table   string   `json:"table"`
		Columns []string `json:"columns,omitempty"`
	} `json:"references"`
}

// Attrs represents common attributes that can be applied to schemas, tables, and columns.
// These are typically dialect-specific metadata.
type Attrs struct {
	Comment string `json:"comment,omitempty"`
	Charset string `json:"charset,omitempty"`
	Collate string `json:"collate,omitempty"`
}
