version: "2"
plugins:
  - name: gen-queries
    process:
      cmd: "true"
sql:
  - schema: "schema/migration"
    queries: "ent/query"
    engine: "postgresql"
    codegen:
      - plugin: gen-queries
        out: "ent/query"
        options:
          queries:
            - "ListUsers"
            - "CopyUsers"
            - "GetUserByEmail"
